### ISSUE TITLE
Error on ArchLinux  after upgrade

### ISSUE THREAD

**Issue by AndrGutierrez** [Mange/rtl8192eu-linux-driver#274]
I upgraded my arch linux and it says 

`missing 5.17.9-arch1-1 kernel modules tree for module rtl8192eu/1.0`

My system does not recognize my wifi adapter anymore, is there a solution or do I have to wait for a driver update?

**Comment by CGarces** [comment]
The code should wok on 5.17.x since #263

I assume that you are using some AUR package like https://aur.archlinux.org/packages/rtl8192eu, you are not building the module as instructed in the [Reamde.md](https://github.com/Mange/rtl8192eu-linux-driver#building-and-installing-using-dkms)

You should send your questions to the comments section on the AUR package

**Comment by AndrGutierrez** [comment]
No, I cloned this repo and installed it as it said in the readme, also when I run dkms install says that it is missing linux-headers 5.16.11
