### ISSUE TITLE
I already installed the driver, but I can not connect to a wifi network

### ISSUE THREAD

**Issue by MSFHacker** [Mange/rtl8192eu-linux-driver#46]
Hello, i have a TP-LINK adapter WN823N connect it to kali linux ande install this driver https://github.com/Mange/rtl8192eu-linux-driver.

Before installing the driver i only had one or two networks to "reach" because i did not have a good signal and it was impossible to connect to a network, after installing the driver mentioned above restart my kali linux and when i select, select networks , more networks came out and with good signal then i proceeded to connect to my wifi network, i put the key and it did not connect i stayed there loading, i tried to navigate and i did not have access.

someone help me please

**Comment by nomadmzl** [comment]
Hi, try with `sudo depmod -a` if it doesn't works, so it will sound dumb but try to unplug and plug again your dongle.

**Comment by scdas141** [comment]
Open “/etc/modules” from Root File Manager by a text-editor (Leafpad, Gedit. etc..)

It will be something like this..

[http://i.imgur.com/RaUT2V9.png](http://i.imgur.com/RaUT2V9.png)

Edit and Add an entry 8192eu as shown below:

[http://i.imgur.com/1KCEjB4.png](http://i.imgur.com/1KCEjB4.png)

Restart ur pc & it should work fine.. for details:

[https://scdas141.wordpress.com/2017/01/28/how-to-compile-mangertl8192eu-linux-driver-driver/](https://scdas141.wordpress.com/2017/01/28/how-to-compile-mangertl8192eu-linux-driver-driver/)

PS. Remember to copy & paste the links as github does not allow clickable links:

**Comment by nomadmzl** [comment]
@scdas141 the links are down.

**Comment by scdas141** [comment]
@nomadmzl 

Hi.. The links are not down, I have tested them myself.. 

The only thing is github does not allow clickable links. You will have to copy & paste the links.. Select the link, right click copy - not copy link - and paste into a new tab..

**Comment by xx7y7xx** [comment]
@scdas141 Markdown syntax for a link should be:

```
[http://i.imgur.com/1KCEjB4.png](http://i.imgur.com/1KCEjB4.png)
```

OR

```
[Open “/etc/modules” from Root File Manager by a text-editor](http://i.imgur.com/1KCEjB4.png)
```

**Comment by scdas141** [comment]
@xxd3vin 
Thx bro for the formatting help..

@nomadmzl 
Links fixed.. hope it helps..

**Comment by xx7y7xx** [comment]
@scdas141 I try your method on one of my workstations (Ubuntu 17.04, Linux kernel 4.10.0-30), it worked, thanks.

**Comment by scdas141** [comment]
@xxd3vin
Glad it helped.. Thx to u too.. :-))

**Comment by milomak** [comment]
where can i go to get help with the following (DWA-131 rev E1 v5.02 running rtl8192eu)

debian sid and a backports 4.9 kernel

`nmcli dev wifi list`
shows the list of wifi connections. and shows mine (WPA2-PSK-AES)


`nmcli device wifi connect SSID-Name password wireless-password`
tells me "Secrets were required, but not provided"

the password is of course correct (disconnected my phone and reestablished a connection to the router)

**Comment by scdas141** [comment]
@milomak 

[https://scdas141.wordpress.com/2017/01/28/how-to-compile-mangertl8192eu-linux-driver-driver/](https://scdas141.wordpress.com/2017/01/28/how-to-compile-mangertl8192eu-linux-driver-driver/)

**Comment by milomak** [comment]
@scdas141 

I used the dkms method to install and the driver is loaded as when I run lsmod I can see 8192eu module. I ran the dkms module in the 4.9 kernel I am running.

Are you saying run make and make install will have a different outcome to building and installing using dkms? 

I can see the wireless card if I run ifconfig. I am able to run the nmcli command. It sees my wifi and those around. It's connect to the router that's the issue.

Or have I missed something in the link you provided?

edit - this may be obvious but should I be using the key generated by wpapassphrase for the password?
 
edit - it must be something with the version of NetworkManager because wicd connected

**Comment by scdas141** [comment]
@milomak 

run `lshw -c network` as root to verify the wireless driver your kernel is using.. 

Even if your install is succesful, whether by make or dkms (you can use either), the linux kernel will use the in-built default rtl8xxxu driver instead of the 8192eu..

To disable the rtl8xxxu driver, after installation open `etc/modprobe.d` in a root folder and create a new file `rtl8xxxu-blacklist.conf` -- edit it with a text editor (leafpad, mousepad etc..) and add these lines:

```
# Do not load the 'rtl8xxxu' module on boot.
blacklist rtl8xxxu
```
Screenshots:
[etc/modprobe.d](http://i.imgur.com/0Cr1aQG.png)

[rtl8xxxu-blacklist.conf](http://i.imgur.com/9CeQx9Y.png)

Save it and restart the system and your connection will work just fine..

Verify that the wireless module loaded is 8192eu by running `lshw -c network`

**Comment by shvchk** [comment]
Having a similar problem: driver installs just fine, I can connect to open WiFi network (i.e. without password), but for password protected network (WPA2-PSK/AES) Network Manager just keeps asking password again and again (system log says `4-Way Handshake failed - pre-shared key may be incorrect`, but I'm 100% sure it is correct, I can connect with this password from other devices, I even tried copy-pasting it to avoid typos or other input problems).

Driver was installed with DKMS, then added to `/etc/modules`, other driver was blacklisted, then system was rebooted. I'm using KDE, but this problem probably isn't DE related, as I've also tried connecting from console with `nmtui-connect` with the same result. I've also tried this card on another computer (laptop) with the same setup and same result, and on Windows, where it works fine.

Any ideas what could be wrong?

```
> cat /etc/issue
Ubuntu 17.04 \n \l

> uname -rv
4.10.0-32-generic #36-Ubuntu SMP Tue Aug 8 12:10:06 UTC 2017
```

**Comment by milomak** [comment]
i don't think it's a case of the driver not loading properly. I haven't
blacklisted anything but yet this is the only driver running

lshw -c network
  *-network
       description: Wireless interface
       physical id: 1
       bus info: usb@2:3
       logical name: wlx542aa2b82afb
       serial: 54:2a:a2:b8:2a:fb
       capabilities: ethernet physical wireless
       configuration: broadcast=yes driver=rtl8192eu ip=192.168.1.115
multicast=yes wireless=IEEE 802.11bgn

lsmod | grep rtl returns nothing

lsmod | grep 8192
8192eu               1093632  0
cfg80211              598016  1 8192eu
snd_hda_core           81920  5
snd_hda_intel,snd_hda_codec,snd_hda_codec_hdmi,snd_hda_codec_generic,snd_hda_codec_via
ehci_hcd               81920  1 ehci_pci
usbcore               249856  6
usbhid,ehci_hcd,8192eu,ohci_pci,ohci_hcd,ehci_pci

**Comment by karl6994** [comment]
I encountered the same issue - I just edited /etc/modules & am rebooting as we speak. 
Hoping it works! I'm running Debian 9 Stretch, but its upgraded to the Debian Buster repo.

**Comment by karl6994** [comment]
Yeah... This isn't working... Same problem, it shows the networks & appropriately has the ranges displayed, but I still can't make it work :( I've tried everything listed here and on the links that were listed here also..

**Comment by CGarces** [comment]
Hi.
Can any one confirm if the solution proposed by @IIETP at #48 fix the issue?

> To fix this you need edit NetworkManager config file:
> 
> `sudo nano /etc/NetworkManager/NetworkManager.conf`
> 
> and add below 2 lines:
> 
> `[device]`
> `wifi.scan-rand-mac-address=no`

**Comment by shvchk** [comment]
Yeah, this fixed my issue indeed! Thanks!

Relevant [Launchpad issue](https://bugs.launchpad.net/ubuntu/+source/network-manager/+bug/1681513) and [Network Manager issue](https://bugzilla.gnome.org/show_bug.cgi?id=777523).

**Comment by CGarces** [comment]
Close the issue with the solution proposed at #48

**Comment by juniorhero** [comment]
@scdas141  thanks man
you saved me

**Comment by scdas141** [comment]
@juniorhero Really dude, it's nothing--

**Comment by it-is-wednesday** [comment]
@scdas141 Thank you so much!
For search engine users on Arch/Antergos/Manjaro, the following command should set you:
`su -c ' echo "8192eu" > /etc/modules-load.d/wifi-driver.conf'`

Note: on manjaro, if you installed your drivers using Manjaro Hardware Detection, you'll have to edit `/etc/modules-load.d/mhwd-gpu.conf` and add `8192eu` to the beginning of the file

**Comment by its-wednesday** [comment]
@scdas141 Thank you so much!
For search engine users on Arch/Antergos, the following command should set you:
`su -c ' echo "8192eu" > /etc/modules-load.d/wifi-driver.conf'`

**Comment by leesei** [comment]
I'm using TP-LINK TN-WN826N, installed the rtl8192eu driver as DKMS module. The driver loads fine on boot but I'm getting authentication timeout when connecting to access point with WPA2-PSK.

It turns out the kernel built-in `rtl8xxxu` module was interfering with `rtl8192eu` (both are loaded when I plug in the dongle).

Here's a one-liner to blacklist `rtl8xxxu`:
```sh
sudo su
mkdir -p /etc/modprobe.d
cat << EOF > /etc/modprobe.d/rtl8xxxu-blacklist.conf
# Do not load the 'rtl8xxxu' module on boot.
blacklist rtl8xxxu
EOF
```

**Comment by LautaroLobo12** [comment]
@scdas141 sorry to bother you. I installed the new driver, addedit to the modules file, also blacklisted the rtl8xxxu driver... and yet nothing works. With the rtl8xxxu driver I can't connect to wifi, it keeps trying to connect to any wifi network, and without it (blacklisted) there is no wireless connection available, lshw does not show it, just shows the ethernet.

edit: modprobe-ing the rtl8192eu driver shows a not found error, may be it's somehow not correctly installed?

Any clue? What may be causing this issue? I would love a solution but knowing what to look at would be also lovely.

Regards,
Lautaro.-

**Comment by CGarces** [comment]
@LautaroLobo12 please try this:

Edit NetworkManager config file:

`sudo nano /etc/NetworkManager/NetworkManager.conf
`
and add below 2 lines:

```
[device]
wifi.scan-rand-mac-address=no
```

**Comment by LautaroLobo12** [comment]
Thanks for answering men.

Well, those lines are already there... there is no need to add nothing because those lines came by default it seems. 

edit: Nothing worked, installed Pop!_OS... almost the same, but in here connects whenever it wants to, and works slowly if connected. I'll be buying a wifi usb extender, hope it works.
