### ISSUE TITLE
Build not working if cross compile

### ISSUE THREAD

**Issue by Alex66955** [Mange/rtl8192eu-linux-driver#49]
When I try to cross compile this driver for an IMX6.
The build process stops without any error.

Is cross compile supported by this driver?

```
make ARCH=arm CROSS_COMPILE=arm-v7a-linux-gnueabihf- -C /data/TQ-DEV/TQMa6x.BSP.SW.SRC.Snapshot-20161219/platform-ngc/build-target/kernel-header-4.1/ M=/data/TQ-DEV/TQMa6x.BSP.SW.SRC.Snapshot-20161219/local_src/rtl_module modules 
make: Verzeichnis „/data/TQ-DEV/TQMa6x.BSP.SW.SRC.Snapshot-20161219/platform-ngc/build-target/kernel-header-4.1“ wird betreten

  WARNING: Symbol version dump ./Module.symvers
           is missing; modules will have no dependencies and modversions.

  Building modules, stage 2.
  MODPOST 0 modules
make: Verzeichnis „/data/TQ-DEV/TQMa6x.BSP.SW.SRC.Snapshot-20161219/platform-ngc/build-target/kernel-header-4.1“ wird verlassen
```

**Comment by CGarces** [comment]
Hi.

Which branch are you using ? `master` or `realtek-4.4`?

Cross compile must work, this driver is used by projects like OpenElec and LibreElec for all architectures, including IMX6.

Based on the [code from LibreELEC](https://github.com/LibreELEC/LibreELEC.tv/blob/master/projects/imx6/options#L51-L73) `master` branch compiles with 3.14, 4,4, 4.8 and 4.10.

I have tested the `realtek-4.4` with the LibreELEC toolchain and kernel 4.4 and look good for me.

**Comment by masterzorag** [comment]
@Alex66955 cross-compile is supported, as build out-of-tree is supported;
Your Warning is just a warning, but you are building against kernel-headers instead of full kernel-sources;
Example:
```sh
blackbox RTL8192EU-linux # pwd
/Storage/RTL8192EU-linux

blackbox RTL8192EU-linux # make KSRC=/Archive/linux-4.12.10
make ARCH=x86_64 CROSS_COMPILE= -C /Archive/linux-4.12.10 M=/Storage/RTL8192EU-linux  modules
make[1]: Entering directory '/Archive/linux-4.12.10'

  WARNING: Symbol version dump ./Module.symvers
           is missing; modules will have no dependencies and modversions.
...

blackbox RTL8192EU-linux # ls -l 8192eu.ko 
-rw-r--r-- 1 root root 2358944 Sep  6 10:15 8192eu.ko
```
So, try just appending KSRC=/path/to/kernel-source to your `make` invocation, like this:

`make ARCH=arm CROSS_COMPILE=arm-v7a-linux-gnueabihf- KSRC=/path/to/kernel-source`

Note that:
- **_at least_** `make modules_prepare` has to be called (on kernel-source) **_before_** building Realtek module!
- you have to change target into [Makefile](https://github.com/Mange/rtl8192eu-linux-driver/blob/master/Makefile#L68) module source

Also, consider moving to linux-4.4 if you get any more issues.

**Comment by Alex66955** [comment]
Thank you very much.
It is working now and I could test the driver in Client and AP-Mode!

**Comment by rohitsay89** [comment]
Thanks for the explanation above, just wanted to know how to locate the kernel folder in the beaglebone black. As I am trying to build the drivers for the same beaglebone black, do I need to mention the kernel files ?
